
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'try to add using FlutLab Firebase Configuration',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyNxONKFXA_fZyG32LTgZeB7vX1S0OmjA',
    iosBundleId: 'com.example.ecommerceplatform',
    appId: '1:357350388370:ios:580fb32317b7dfe3a7ec4b',
    storageBucket: 'ecommerceplatform-96de1.appspot.com',
    messagingSenderId: '357350388370',
    iosClientId: 'undefined',
    projectId: 'ecommerceplatform-96de1'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgf_laeZFa4vKnofSzqZ0lV3tXKrjrtBo',
    appId: '1:357350388370:android:188ebb84ddd8e6b9a7ec4b',
    messagingSenderId: '357350388370',
    projectId: 'ecommerceplatform-96de1',
    storageBucket: 'ecommerceplatform-96de1.appspot.com'
  );
}
